site_name: Calorie Counter

nav:
  - Home: index.md
  - Visão do Produto e Projeto: 
    - Visão do Produto: visao_produto_projeto\processo_dev\processo_dev.md
    - Visão do Projeto: visao_produto_projeto\visao_produto\visao_produto.md
    - Processo de Desenvolvimento: visao_produto_projeto\processo_dev\processo_dev.md
  - Entregas:
    - Entrega 1: 
      - História da Facção: entregas\entrega1\historia_faccao.md
      - Lições Aprendidas: entregas\entrega1\licoes_aprendidas.md

  

theme:
  name: material
  language: "pt"
  favicon: assets/logo.ico