site_name: Calorie Counter

nav:
  - Home: index.md
  - Visão do Produto e Projeto: 
    - Visão do Produto: visao_produto_projeto/visao_produto/visao_produto.md
    - Visão do Geral do Projeto: visao_produto_projeto/visao_projeto/visao_projeto.md
    - Processo de Desenvolvimento: visao_produto_projeto/processo_dev/processo_dev.md
  - Entregas:
    - Entrega 1: entregas/entrega1.md
  

theme:
  name: material
  language: "pt"
  favicon: assets/logo.ico