site_name: Calorie Counter

repo_name: "2024.1-CalorieExplorer"
repo_url: "https://github.com/mdsreq-fga-unb/2024.1-CalorieExplorer"

nav:
  - Início: index.md
  - Visão do Produto e Projeto:
    - Visão do Produto: visao_produto_projeto/visao_produto/visao_produto.md
    - Visão do Geral do Projeto: visao_produto_projeto/visao_projeto/visao_projeto.md
    - Processo de Desenvolvimento: visao_produto_projeto/processo_dev/processo_dev.md
  - Backlog:
    - Definições: backlog/definicoes.md
    - Backlog do Produto: backlog/req_criterios.md
    - MPV: backlog/mpv.md
  - Apresentações:
    - Missão 1:
      - Apresentação: apresentacoes/missao1/apresentacao1.md
      - Lições Aprendidas: apresentacoes/missao1/licoes_aprendidas.md
    - Missão 2: 
      - Backlog: apresentacoes/missao2/backlog.md
    - Missão 3:
      - PBB e PBI: apresentacoes/missao3/pbb_pbi.md
      - Lições Aprendidas: apresentacoes/missao3/licoes_aprendidas3.md
  - Unidade 3:
    - Atividade do Product Backlog Building (PBB): unidade/pbb.md
    - Atividade do User Stories Mapping (USM): unidade/usm.md
  - Entregas:
    - Entregas Missão 1: 
      - História da Facção: entregas/entrega1/historia_faccao.md
      - Processos ESW: entregas/entrega1/slides_esw.md

  

theme:
  name: material
  language: "pt"
  favicon: assets/logo.ico
  logo: assets/logo.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: "Montserrat"
    code: "sans-serif"
extra_css:
  - stylesheets/extra.css
