name: gitpages_workflow

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          path: |
            ~/.cache/pip
            .cache

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material

      - name: Build site
        run: |
          cd calorie-counter-docs
          mkdocs build

      - name: Deploy to GitHub Pages
        run: |
          cd calorie-counter-docs
          mkdocs gh-deploy --force
